### ISSUE TITLE
Installer not findable on Rails 5.1

### ISSUE THREAD

**Issue by askl56** [AlchemyCMS/alchemy-solidus#24]
When runnning `bin/rails g alchemy:solidus:install` on a pre-existing Rails installation:

```ams at andews-mbp in ~/Dropbox/code/bolt/bmc_solidus on upgrade/cms-upgrade [?]
❯ bin/rails g alchemy:solidus:install                                                                                                                                                     860ms
Running via Spring preloader in process 87197
Traceback (most recent call last):
	46: from -e:1:in `<main>'
	45: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	44: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	43: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `load'
	42: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	41: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:286:in `block in load'
	40: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	39: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	38: from /Users/ams/Dropbox/code/bolt/bmc_solidus/bin/rails:9:in `<main>'
	37: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	36: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	35: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	34: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	33: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	32: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	31: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	30: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	29: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	28: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<main>'
	27: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	26: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	25: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	24: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	22: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/commands/generate/generate_command.rb:24:in `perform'
	21: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/generators.rb:267:in `invoke'
	20: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/generators.rb:250:in `find_by_namespace'
	19: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:77:in `lookup'
	18: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:77:in `each'
	17: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:78:in `block in lookup'
	16: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:78:in `each'
	15: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:82:in `block (2 levels) in lookup'
	14: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	13: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	12: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	11: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	10: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 9: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 8: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 7: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 6: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 5: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/alchemy-solidus-289929571343/lib/generators/alchemy/solidus/install/install_generator.rb:7:in `<main>'
	 4: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	 3: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	 2: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	 1: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- generators/alchemy/devise/install/install_generator (LoadError)```

**Comment by askl56** [comment]
Agreed on `spring` 👍 

Will test and get back to you.

**Comment by tvdeyen** [comment]
@askl56 TIL that `rescue` does not rescue `LoadError`. Will provide a fix soon. I currently have a problem with the test suite. It currently does not build with Solidus 2.5 and 2.6, because of dependency issue, that are solved with Alchemy 4.0.4 (which I released two days ago)

**Comment by askl56** [comment]
```ams at andews-mbp in ~/Dropbox/code/bolt/bmc_solidus on upgrade/cms-upgrade
❯ spring stop                                                                                                                                                                             12:07
Spring stopped.

ams at andews-mbp in ~/Dropbox/code/bolt/bmc_solidus on upgrade/cms-upgrade
❯ DISABLE_SPRING=1 bin/rails g alchemy:solidus:install                                                                                                                                    404ms
fish: Unsupported use of '='. To run 'bin/rails' with a modified environment, please use 'env DISABLE_SPRING=1 bin/rails…'

ams at andews-mbp in ~/Dropbox/code/bolt/bmc_solidus on upgrade/cms-upgrade
❯ env DISABLE_SPRING=1 bin/rails g alchemy:solidus:install                                                                                                                                12:07
Traceback (most recent call last):
	37: from bin/rails:9:in `<main>'
	36: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	35: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	34: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	33: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	32: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	31: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	30: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	29: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	28: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<main>'
	27: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	26: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	25: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	24: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	23: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	22: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/commands/generate/generate_command.rb:24:in `perform'
	21: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/generators.rb:267:in `invoke'
	20: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/generators.rb:250:in `find_by_namespace'
	19: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:77:in `lookup'
	18: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:77:in `each'
	17: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:78:in `block in lookup'
	16: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:78:in `each'
	15: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.1/lib/rails/command/behavior.rb:82:in `block (2 levels) in lookup'
	14: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	13: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	12: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	11: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	10: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 9: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 8: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	 7: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 6: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 5: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/alchemy-solidus-289929571343/lib/generators/alchemy/solidus/install/install_generator.rb:7:in `<main>'
	 4: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	 3: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	 2: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	 1: from /Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/ams/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- generators/alchemy/devise/install/install_generator (LoadError)```

**Comment by askl56** [comment]
Still not working, any ideas?

**Comment by askl56** [comment]
Should I fork and remove the line you referenced?

**Comment by askl56** [comment]
@tvdeyen the install went fine I think? Asking me to change `application.html.erb` but now getting this:

```❯ bundle exec rails s -p 5000                                                                                                                                                             12:30
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:5000
=> Run `rails server -h` for more startup options

AlchemyCMS cannot find any user class!

Please add a user class and tell Alchemy about it or, if you don't want
to create your own class, add the `alchemy-devise` gem to your Gemfile.

gem 'alchemy-devise', '~> 2.1.0'
Exiting```

Despite the initializer stating:

```
require 'alchemy/solidus/use_solidus_layout'

Alchemy.user_class_name = 'Spree::User'
Alchemy.current_user_method = :spree_current_user
```
