### ISSUE TITLE
Unable to load application: NameError: uninitialized constant Alchemy::Ingredient

### ISSUE THREAD

**Issue by afdev82** [AlchemyCMS/alchemy-solidus#79]
**Describe the bug**
The gem is not compatible with Alchemy v5.2.1 anymore.

**To Reproduce**

- Install the gem using the latest main branch (I used the branch of PR #76 to be able to use it with Solidus v3)
- starts the application
- I get the following error:

```
2021-07-08T11:25:27.287428+00:00 app[web.2]: [heroku-exec] Starting
2021-07-08T11:25:28.612249+00:00 app[web.2]: [3] Puma starting in cluster mode...
2021-07-08T11:25:28.612272+00:00 app[web.2]: [3] * Puma version: 5.3.2 (ruby 2.7.3-p183) ("Sweetnighter")
2021-07-08T11:25:28.612273+00:00 app[web.2]: [3] *  Min threads: 5
2021-07-08T11:25:28.612273+00:00 app[web.2]: [3] *  Max threads: 5
2021-07-08T11:25:28.612291+00:00 app[web.2]: [3] *  Environment: production
2021-07-08T11:25:28.612309+00:00 app[web.2]: [3] *   Master PID: 3
2021-07-08T11:25:28.612311+00:00 app[web.2]: [3] *      Workers: 2
2021-07-08T11:25:28.612350+00:00 app[web.2]: [3] *     Restarts: (✔) hot (✖) phased
2021-07-08T11:25:28.612353+00:00 app[web.2]: [3] * Preloading application
2021-07-08T11:25:35.329115+00:00 app[web.2]: DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. `parent_name` is deprecated and will be removed in Rails 6.1. (called from block in <main> at /app/config/environments/production.rb:68)
2021-07-08T11:25:43.186267+00:00 app[web.2]: [3] ! Unable to load application: NameError: uninitialized constant Alchemy::Ingredient
2021-07-08T11:25:43.186339+00:00 app[web.2]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.7.0/bin/puma)
2021-07-08T11:25:43.186561+00:00 app[web.2]: /app/vendor/bundle/ruby/2.7.0/bundler/gems/alchemy-solidus-e96721ee71da/app/models/alchemy/ingredients/spree_product.rb:5:in `<module:Ingredients>': uninitialized constant Alchemy::Ingredient (NameError)
2021-07-08T11:25:43.186580+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/bundler/gems/alchemy-solidus-e96721ee71da/app/models/alchemy/ingredients/spree_product.rb:4:in `<module:Alchemy>'
2021-07-08T11:25:43.186581+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/bundler/gems/alchemy-solidus-e96721ee71da/app/models/alchemy/ingredients/spree_product.rb:3:in `<main>'
2021-07-08T11:25:43.186584+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
2021-07-08T11:25:43.186602+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
2021-07-08T11:25:43.186602+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
2021-07-08T11:25:43.186620+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
2021-07-08T11:25:43.186623+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
2021-07-08T11:25:43.186625+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2021-07-08T11:25:43.186642+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
2021-07-08T11:25:43.186642+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
2021-07-08T11:25:43.186674+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
2021-07-08T11:25:43.186675+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:481:in `block (2 levels) in eager_load!'
2021-07-08T11:25:43.186675+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:480:in `each'
2021-07-08T11:25:43.186676+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:480:in `block in eager_load!'
2021-07-08T11:25:43.186679+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:477:in `each'
2021-07-08T11:25:43.186679+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:477:in `eager_load!'
2021-07-08T11:25:43.186693+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/engine.rb:356:in `eager_load!'
2021-07-08T11:25:43.186694+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/application/finisher.rb:123:in `each'
2021-07-08T11:25:43.186696+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/application/finisher.rb:123:in `block in <module:Finisher>'
2021-07-08T11:25:43.186702+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `instance_exec'
2021-07-08T11:25:43.186719+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `run'
2021-07-08T11:25:43.186719+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:61:in `block in run_initializers'
2021-07-08T11:25:43.186722+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
2021-07-08T11:25:43.186738+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2021-07-08T11:25:43.186738+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
2021-07-08T11:25:43.186754+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
2021-07-08T11:25:43.186755+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each'
2021-07-08T11:25:43.186758+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `call'
2021-07-08T11:25:43.186775+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
2021-07-08T11:25:43.186775+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
2021-07-08T11:25:43.186778+00:00 app[web.2]: from /app/vendor/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
2021-07-08T11:25:43.186796+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/initializable.rb:60:in `run_initializers'
2021-07-08T11:25:43.186798+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.6/lib/rails/application.rb:363:in `initialize!'
2021-07-08T11:25:43.186801+00:00 app[web.2]: from /app/config/environment.rb:5:in `<top (required)>'
2021-07-08T11:25:43.186803+00:00 app[web.2]: from config.ru:3:in `require'
2021-07-08T11:25:43.186820+00:00 app[web.2]: from config.ru:3:in `block in <main>'
2021-07-08T11:25:43.186820+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
2021-07-08T11:25:43.186823+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
2021-07-08T11:25:43.186850+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
2021-07-08T11:25:43.186850+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
2021-07-08T11:25:43.186851+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/configuration.rb:345:in `load_rackup'
2021-07-08T11:25:43.186851+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/configuration.rb:267:in `app'
2021-07-08T11:25:43.186854+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/runner.rb:143:in `load_and_bind'
2021-07-08T11:25:43.186854+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/cluster.rb:349:in `run'
2021-07-08T11:25:43.186856+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/launcher.rb:181:in `run'
2021-07-08T11:25:43.186869+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/lib/puma/cli.rb:80:in `run'
2021-07-08T11:25:43.186870+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/puma-5.3.2/bin/puma:10:in `<top (required)>'
2021-07-08T11:25:43.186872+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/bin/puma:23:in `load'
2021-07-08T11:25:43.186874+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/bin/puma:23:in `<top (required)>'
2021-07-08T11:25:43.186891+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `load'
2021-07-08T11:25:43.186891+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63:in `kernel_load'
2021-07-08T11:25:43.186894+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:28:in `run'
2021-07-08T11:25:43.186911+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:474:in `exec'
2021-07-08T11:25:43.186912+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2021-07-08T11:25:43.186914+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
2021-07-08T11:25:43.186932+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
2021-07-08T11:25:43.186932+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:30:in `dispatch'
2021-07-08T11:25:43.186949+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
2021-07-08T11:25:43.186949+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:24:in `start'
2021-07-08T11:25:43.186951+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/exe/bundle:49:in `block in <top (required)>'
2021-07-08T11:25:43.186981+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
2021-07-08T11:25:43.186982+00:00 app[web.2]: from /app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/exe/bundle:37:in `<top (required)>'
2021-07-08T11:25:43.186984+00:00 app[web.2]: from /app/bin/bundle:3:in `load'
2021-07-08T11:25:43.186986+00:00 app[web.2]: from /app/bin/bundle:3:in `<main>'
```

**Expected behavior**
The application should start as usual.

**Gems in your `Gemfile`:**
 - `alchemy_cms`: [5.2.1]
 - `solidus` [3.0.1]
 - `rails` [6.0.3.6]

**Comment by tvdeyen** [comment]
Ah, sure. I know what to do :)
Thanks for reporting

**Comment by afdev82** [comment]
Great! So I will wait ;)

**Comment by tvdeyen** [comment]
@afdev82 created #80

**Comment by afdev82** [comment]
Thank you very much!
